default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000

development:
  <<: *default
  database: smalldoor_dev

test:
  <<: *default
  database: smalldoor_test
